export const [
  EXCHANGE_NAME,
  REVIEW_BINDING_KEY,
  REVIEW_QUEUE_NAME,
  REVIEW_RPCQUEUE_NAME,
  PRODUCT_QUEUE_NAME,
] = [
  "E-Commerce",
  "REVIEW",
  "REVIEW_QUEUE",
  "REVIEW_QUEUE_RPC",
  "PRODUCT_QUEUE",
];
