export const { SECRET } = {
  SECRET: "E-commerce",
};

//RABBIT_MQ
export const {
  EXCHANGE_NAME,
  PRODUCT_QUEUE_NAME,
  RABBIT_MQ_URL,
  REVIEW_BINDING_KEY,
  REVIEW_QUEUE_NAME,
  REVIEW_RPCQUEUE_NAME,
  USER_BINDING_KEY,
  USER_QUEUE_NAME,
} = {
  RABBIT_MQ_URL: "http://localhost:15672",
  EXCHANGE_NAME: "E-Commerce",
  REVIEW_BINDING_KEY: "REVIEW",
  REVIEW_QUEUE_NAME: "REVIEW_QUEUE",
  REVIEW_RPCQUEUE_NAME: "REVIEW_QUEUE_RPC",
  PRODUCT_QUEUE_NAME: "PRODUCT_QUEUE",
  USER_QUEUE_NAME: "USER_QUEUE",
  USER_BINDING_KEY: "USER",
};
